// Cladding · self-consistency (dogfood) tests
//
// cladding is a drift-detection tool — it must not silently drift against
// ITSELF. A prior audit found exactly that "Vacuous Green" pattern: docs
// claimed "26 detectors" while the code shipped 27, and spec.yaml's
// project.version lagged a full minor behind package.json, with no check
// catching either. Those were hand-corrected; this suite locks the
// corrections as permanent, CI-enforced invariants so they cannot regress.
//
// These are cladding-SELF checks (they run against this repo's own files),
// NOT shipped detectors — a general adopting project may legitimately
// version its spec.yaml independently or mention "N detectors" in its own
// docs, so enforcing this on every project would false-fail. Keeping it as
// a self-test gives the reference implementation honesty without imposing
// it on adopters.

import {readFileSync, readdirSync, statSync} from 'node:fs';
import {join} from 'node:path';
import {describe, expect, test} from 'vitest';

import {allDetectors} from '../src/stages/detectors/index.js';
// TIER_STAGES is the SSoT for the Iron Law stage list; importing clad.ts is
// safe because its CLI entry is guarded by `isCliEntry` (no parse on import).
import {TIER_STAGES} from '../src/cli/clad.js';

const ROOT = process.cwd();
const read = (rel: string): string => readFileSync(join(ROOT, rel), 'utf8');

describe('cladding self-consistency (no Vacuous Green against itself)', () => {
  test('prose detector-count claims match the actual detector count', () => {
    const actual = allDetectors.length;
    // Files that state cladding's own detector count. The README badge + prose
    // and the ecosystem SVGs are NOT regenerated by the build, so they have
    // historically lagged the shipped count (37 vs 38 — the original audit's
    // Vacuous Green, recurring). Check EVERY count claim — badge `detectors-<N>`
    // and prose `<N> [drift ]detector(s)` — against allDetectors.length so no
    // hand-maintained surface can silently lag again.
    const files = [
      'spec.yaml',
      'docs/project-context.md',
      'spec/capabilities.yaml',
      'AGENTS.md',
      'README.md',
      'README.ko.md',
      'docs/img/en/ecosystem.svg',
      'docs/img/ko/ecosystem.svg',
    ];
    // group 1 = badge form (`detectors-40`); group 2 = prose (`40 drift detectors`).
    const re = /detectors?-(\d+)|(\d+)\s+(?:drift\s+)?detectors?\b/gi;
    for (const f of files) {
      const matches = [...read(f).matchAll(re)];
      expect(matches.length, `${f} should state a detector count`).toBeGreaterThan(0);
      for (const m of matches) {
        expect(Number(m[1] ?? m[2]), `${f} detector-count claim should equal allDetectors.length`).toBe(actual);
      }
    }
  });

  test('README prose detector-count claims match the actual detector count (F-898783ee)', () => {
    const actual = allDetectors.length;
    // Three README-family files headline cladding's own detector count. Each
    // regex is scoped to that file's HEADLINE phrasing so per-subset counts
    // never false-trip: README.md also says "41 detectors"/"41 detector" and
    // lists bare "10"/"6"/… per-direction cells in the detector table, while
    // src/stages/detectors/README.md discusses the historical upstream
    // "19 detectors" headline and the "3 always-error" / "16 conditional"
    // subsets. Anchoring on "drift detectors" (README) and "detectors are
    // wired" (inventory) captures only the live-count claim in each.
    //
    // README.ko.md (AC-4772bf42): the KO headline mixes Korean and English —
    // "41개 검출기" (Korean noun) plus "41 detector(s)" (English). Anchoring on
    // the English "detector" token captures every numbered claim (all four read
    // 41) while skipping the Korean-noun phrasings and the per-direction "수"
    // table cells (numbers followed by a detector NAME, not the word
    // "detector"), so the KO variant can no longer silently drift from the EN.
    const guards: Array<{file: string; re: RegExp; label: string}> = [
      {file: 'README.md', re: /(\d+)\s+drift detectors/g, label: '"<N> drift detectors"'},
      {file: 'src/stages/detectors/README.md', re: /(\d+)\s+detectors are wired/g, label: '"<N> detectors are wired"'},
      {file: 'README.ko.md', re: /(\d+)\s+(?:drift\s+)?detectors?\b/gi, label: '"<N> [drift] detector(s)" (KO)'},
    ];
    for (const {file, re, label} of guards) {
      const matches = [...read(file).matchAll(re)];
      expect(matches.length, `${file} should state ${label} at least once`).toBeGreaterThan(0);
      for (const m of matches) {
        expect(Number(m[1]), `${file} ${label} claim "${m[0]}" should equal allDetectors.length`).toBe(actual);
      }
    }
  });

  test('README/AGENTS stage-count claims match TIER_STAGES.all.length (F-898783ee)', () => {
    const actual = TIER_STAGES.all.length;
    // README.md says "15-stage"/"15 stages"; AGENTS.md says "15 Iron Law
    // stages". The README regex requires the numeral ADJACENT to "stage(s)"
    // (a single hyphen or space) so the "9 deterministic stages" subset claim
    // never false-trips; the AGENTS regex tolerates the "Iron Law" infix.
    //
    // README.ko.md (AC-4772bf42): the KO stage noun is "단계", which the file
    // ALSO uses for subsets ("3단계"/"9단계" per tier) and setup steps
    // ("1단계"/"2단계"). Anchoring on "<N>단계" immediately followed by
    // "게이트"/"Iron Law" captures only the four total-gate claims (all 15) and
    // never the subset/step counts.
    const guards: Array<{file: string; re: RegExp; label: string}> = [
      {file: 'README.md', re: /(\d+)[-\s]stages?\b/g, label: '"<N>-stage"/"<N> stages"'},
      {file: 'AGENTS.md', re: /(\d+)\s+(?:Iron Law\s+)?stages\b/g, label: '"<N> Iron Law stages"'},
      {file: 'README.ko.md', re: /(\d+)단계\s+(?:게이트|Iron Law)/g, label: '"<N>단계 게이트/Iron Law" (KO)'},
    ];
    for (const {file, re, label} of guards) {
      const matches = [...read(file).matchAll(re)];
      expect(matches.length, `${file} should state ${label} at least once`).toBeGreaterThan(0);
      for (const m of matches) {
        expect(Number(m[1]), `${file} ${label} claim "${m[0]}" should equal TIER_STAGES.all.length`).toBe(actual);
      }
    }
  });

  test('spec.yaml project.version tracks package.json version', () => {
    const pkgVersion = (JSON.parse(read('package.json')) as {version: string}).version;
    const specVersion = read('spec.yaml').match(/^\s*version: "(\d+\.\d+\.\d+)"/m)?.[1];
    expect(specVersion, 'spec.yaml must declare project.version').toBeDefined();
    expect(specVersion).toBe(pkgVersion);
  });

  test('Tier A/B spec files carry the mandated first-line tier banner', () => {
    // docs/ssot-model.md §Header convention mandates a `# Cladding · Tier X`
    // banner as the first line of every managed artifact.
    expect(read('spec.yaml').split('\n')[0]).toMatch(/^#\s*Cladding\s*·\s*Tier A\b/);
    expect(read('spec/architecture.yaml').split('\n')[0]).toMatch(/^#\s*Cladding\s*·\s*Tier B\b/);
    expect(read('spec/capabilities.yaml').split('\n')[0]).toMatch(/^#\s*Cladding\s*·\s*Tier B\b/);
  });
});

describe('glossary is the terminology SSoT (F-7ce18e)', () => {
  // Every public name must carry a glossary row — a name the glossary does
  // not know is an unregistered term and fails here (AC-002). The glossary
  // documents names as `name` (backticked); presence of the backticked token
  // anywhere in the file counts as registered.
  const glossary = read('docs/glossary.md');
  const registered = (name: string): boolean => glossary.includes('`' + name + '`');

  test('every CLI verb registered in clad.ts has a glossary row', () => {
    const cli = read('src/cli/clad.ts');
    // commander registrations: .command('<verb> [args...]') — first word is the verb.
    const verbs = [...cli.matchAll(/\.command\('([a-z]+)[^']*'\)/g)].map((m) => m[1]);
    expect(verbs.length).toBeGreaterThanOrEqual(14);
    for (const v of new Set(verbs)) {
      expect(registered(v), `CLI verb '${v}' is missing from docs/glossary.md`).toBe(true);
    }
  });

  test('every persona file under src/agents/ has a glossary row', () => {
    const ids = readdirSync(join(ROOT, 'src/agents'))
      .filter((f) => f.endsWith('.md') && f !== 'README.md')
      .map((f) => f.replace(/\.md$/, ''));
    expect(ids.length).toBeGreaterThanOrEqual(5);
    for (const id of ids) {
      expect(registered(id), `persona '${id}' is missing from docs/glossary.md`).toBe(true);
    }
  });

  test('every MCP tool registered in server.ts has a glossary row (frozen wire ids)', () => {
    const server = read('src/serve/server.ts');
    const tools = [...server.matchAll(/'(clad_[a-z_]+)'/g)].map((m) => m[1]);
    expect(new Set(tools).size).toBeGreaterThanOrEqual(8);
    for (const t of new Set(tools)) {
      expect(registered(t), `MCP tool '${t}' is missing from docs/glossary.md`).toBe(true);
    }
  });

  test('every event type has a glossary row (frozen wire ids)', () => {
    // Strip // comments BEFORE matching — the union's doc comments quote
    // payload values ('scan_artifacts' etc.) and contain semicolons that
    // would truncate a naive capture.
    const log = read('src/events/log.ts')
      .split('\n')
      .map((l) => l.replace(/\/\/.*$/, ''))
      .join('\n');
    const m = log.match(/export type EventType =([^;]+);/);
    expect(m).not.toBeNull();
    const types = [...m![1].matchAll(/'([a-z_]+)'/g)].map((x) => x[1]);
    expect(types.length).toBeGreaterThanOrEqual(9);
    for (const t of types) {
      expect(registered(t), `event type '${t}' is missing from docs/glossary.md`).toBe(true);
    }
  });

  test('deprecated aliases are documented as aliases pointing at their replacement', () => {
    for (const [oldName, newName] of [
      ['librarian', 'planner'],
      ['specialists', 'developer'],
      ['refine', 'clarify'],
      ['panel', 'status'],
      ['drive', 'run'],
    ]) {
      const row = glossary.split('\n').find((l) => l.includes('`' + oldName + '`') && l.includes('alias'));
      expect(row, `'${oldName}' must have an alias row`).toBeDefined();
      expect(row, `'${oldName}' alias row must name '${newName}'`).toContain('`' + newName + '`');
    }
  });

  test('no source file carries a raw NUL byte (git would treat it as binary)', () => {
    // v0.7.0 shipped src/graph/model.ts with literal 0x00 chars inside a
    // template literal — git's binary heuristic then hid the ENTIRE file from
    // every diff/blame/review ("Bin 0 -> 9363 bytes"). The escape sequence
    // spelling (backslash-u-0000) is byte-identical at runtime; only the raw byte is
    // banned. Scans the source tree, not node_modules/dist.
    const offenders: string[] = [];
    const walk = (dir: string): void => {
      for (const name of readdirSync(join(ROOT, dir))) {
        if (name.startsWith('.') || name === 'node_modules' || name === 'dist') continue;
        const rel = join(dir, name);
        let stat;
        try {
          stat = statSync(join(ROOT, rel));
        } catch {
          continue;
        }
        if (stat.isDirectory()) walk(rel);
        else if (/\.(ts|tsx|mts|cts|js|mjs|md|yaml|yml|json|css)$/.test(name)) {
          if (readFileSync(join(ROOT, rel)).includes(0)) offenders.push(rel);
        }
      }
    };
    for (const top of ['src', 'tests', 'spec', 'docs', 'skills', 'scripts']) walk(top);
    expect(offenders, `raw 0x00 byte(s) found — use the '\\u0000' escape instead: ${offenders.join(', ')}`).toEqual([]);
  });
});
