// Cladding · `clad hook <event>` — host hook protocol adapter (F-1d23a6)
//
// Claude Code lifecycle hooks invoke this verb with the event payload on
// stdin and read the protocol response from stdout. The contract:
//
//   - stdin may be empty or malformed JSON → treated as `{}`
//   - stdout is the ONLY protocol surface: plain text becomes injected
//     context (SessionStart / UserPromptSubmit / PostToolUse), and a
//     `{"decision":"block","reason":…}` JSON line blocks (PreToolUse / Stop)
//   - ALWAYS exit 0 — a crashing hook must never brick the host session,
//     so every handler is wrapped and an internal error prints nothing
//
// This file moves cladding's engagement layer from prose (CLAUDE.md asking
// the model to behave) to structure (the host mechanically injecting the
// spec map and mechanically blocking hand-flipped `status: done`).
//
// HONEST LIMIT: PreToolUse only sees Edit/Write/MultiEdit tool calls — a
// YAML edit made THROUGH Bash (sed, heredoc, git apply) bypasses the block
// lane entirely. The Stop hook's deterministic trio is the second lane that
// catches the result after the fact (annotation-free done trips MISSING_TESTS
// etc.). Blocking is lane one, post-hoc detection is lane two; neither alone.
//
// @see plugins/claude-code/hooks/hooks.json — the shipped wiring (AC-03da31).
// @see spec/features/host-hooks-1d23a6.yaml — the contract.

import {createHash} from 'node:crypto';
import {existsSync, mkdirSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {dirname, isAbsolute, join} from 'node:path';
import process from 'node:process';

import {parse as parseYaml} from 'yaml';

import {latestEventOfType, recordEvent} from '../events/log.js';
import type {Intent} from '../router/intent.js';
import {suggestIntent} from '../router/intent.js';
import {runArch} from '../stages/arch.js';
import {runDrift} from '../stages/drift.js';
import {runSecret} from '../stages/secret.js';

// --- shared helpers ----------------------------------------------------

function asRecord(v: unknown): Record<string, unknown> {
  return typeof v === 'object' && v !== null ? (v as Record<string, unknown>) : {};
}

function asString(v: unknown): string {
  return typeof v === 'string' ? v : '';
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1)}…`;
}

const WRITE_TOOLS: ReadonlySet<string> = new Set(['Edit', 'Write', 'MultiEdit']);

// --- SessionStart — context card ---------------------------------------

interface IndexDoc {
  readonly features?: Record<string, {readonly slug?: unknown; readonly status?: unknown} | null>;
}

interface SpecDoc {
  readonly inventory?: {readonly features?: unknown; readonly scenarios?: unknown};
  readonly features?: readonly {readonly id?: unknown; readonly slug?: unknown; readonly status?: unknown}[];
  readonly scenarios?: readonly unknown[];
}

const POLICY_LINE =
  'policy: spec is SSoT — author shards via clad_create_feature; flip done only via clad done; verify with clad_run_gate';

/**
 * Renders the SessionStart context card — the spec map injected mechanically
 * instead of relying on the model greping CLAUDE.md. Prints nothing when the
 * project is not under cladding (no spec.yaml).
 */
function renderSessionStartCard(cwd: string): string {
  const specPath = join(cwd, 'spec.yaml');
  if (!existsSync(specPath)) return '';
  let spec: SpecDoc = {};
  try {
    spec = (parseYaml(readFileSync(specPath, 'utf8')) as SpecDoc | null) ?? {};
  } catch {
    /* unparseable spec → counts degrade to the inventory defaults below */
  }

  let total = 0;
  let done = 0;
  const inProgress: {id: string; slug: string}[] = [];
  let counted = false;

  // Primary source: spec/index.yaml — one `F-xxx: {slug, status, modules: N}`
  // line per feature, regenerated by `clad sync` (F-37b4a8).
  const indexPath = join(cwd, 'spec', 'index.yaml');
  if (existsSync(indexPath)) {
    try {
      const idx = (parseYaml(readFileSync(indexPath, 'utf8')) as IndexDoc | null) ?? {};
      for (const [id, row] of Object.entries(asRecord(idx.features))) {
        total++;
        const entry = asRecord(row);
        const status = asString(entry.status);
        if (status === 'done') done++;
        if (status === 'in_progress') inProgress.push({id, slug: asString(entry.slug) || id});
      }
      counted = true;
    } catch {
      /* unreadable index → fall through to spec.yaml */
    }
  }
  // Fallbacks: inline features[] (unsharded spec), then the auto-maintained
  // inventory block (sharded spec whose index has not been generated yet).
  if (!counted && Array.isArray(spec.features)) {
    for (const f of spec.features) {
      total++;
      const entry = asRecord(f);
      const status = asString(entry.status);
      const id = asString(entry.id) || '?';
      if (status === 'done') done++;
      if (status === 'in_progress') inProgress.push({id, slug: asString(entry.slug) || id});
    }
    counted = true;
  }
  if (!counted) {
    const n = Number(spec.inventory?.features);
    total = Number.isFinite(n) ? n : 0;
  }
  const scenariosInventory = Number(spec.inventory?.scenarios);
  const scenarios = Number.isFinite(scenariosInventory)
    ? scenariosInventory
    : Array.isArray(spec.scenarios)
      ? spec.scenarios.length
      : 0;

  const lines: string[] = [
    `cladding: ${total} features (${done} done, ${inProgress.length} in progress) · ${scenarios} scenarios`,
  ];
  if (inProgress.length > 0) {
    lines.push(`in progress: ${inProgress.slice(0, 3).map((f) => `${f.id} ${f.slug}`).join(', ')}`);
  }
  const gate = latestEventOfType(cwd, 'gate_run');
  if (gate) {
    const head = asString(gate.payload.head).length > 0 ? asString(gate.payload.head).slice(0, 8) : 'no-git';
    const red = gate.payload.anyFailed === true || (typeof gate.payload.worst === 'number' && gate.payload.worst > 0);
    lines.push(`last gate: ${asString(gate.payload.tier) || '?'} strict=${gate.payload.strict === true} → ${red ? 'RED' : 'GREEN'} @ ${head}`);
  }
  const blockPath = join(cwd, '.cladding', 'stop-block.json');
  if (existsSync(blockPath)) {
    try {
      const sb = JSON.parse(readFileSync(blockPath, 'utf8')) as {count?: unknown; first?: unknown};
      lines.push(`unresolved stop-block: ${Number(sb.count ?? 0)} finding(s) — ${asString(sb.first) || 'unknown'}`);
    } catch {
      /* unreadable block file → omit the resurface line */
    }
  }
  lines.push(POLICY_LINE);
  return lines.join('\n');
}

// --- UserPromptSubmit — one-line routing suggestion ---------------------

const INTENT_HINTS: Readonly<Partial<Record<Intent, string>>> = {
  run: 'feature cycle: shard → implement → tests → clad done',
  check: 'verify with clad_run_gate or clad check --strict',
  sync: 'clad sync validates + heals the spec',
  init: 'scaffold with /cladding:init',
};

// Completion claims were the WEAKEST measured engagement surface (the 0.6.0
// engagement sample failed the entire c-bucket on both arms): "looks done,
// wrap it up" produced no gated `clad done`. A dedicated card beats the
// generic check suggestion here (F-95a096).
const COMPLETION_CLAIM =
  /\b(wrap (it |this )?up|looks? (all )?done|mark (it |this |.{0,24})?done|finish(ed)? (it|this|up)|ship it)\b|마무리|완료 ?처리|끝난 ?것 ?같|완료해/i;

/** Renders the one-line routing suggestion, or nothing for unclassifiable prompts. */
function renderPromptSuggestion(input: unknown): string {
  const prompt = asString(asRecord(input).prompt);
  if (prompt.length === 0) return '';
  if (COMPLETION_CLAIM.test(prompt)) {
    return (
      'cladding: completion is EARNED, not declared — run `clad done <F-id>` ' +
      '(the strict gate flips it only when GREEN); in-progress ids are one grep away in spec/index.yaml'
    );
  }
  const intent = suggestIntent(prompt);
  const hint = intent ? INTENT_HINTS[intent] : undefined;
  if (!intent || !hint) return '';
  return `cladding: this looks like ${intent} work — ${hint}`;
}

// --- PreToolUse — structural guard on spec edits ------------------------

const FEATURE_SHARD_PATH = /spec[\\/]features[\\/][^\\/]+\.ya?ml$/;
const SEQUENTIAL_SHARD_PATH = /spec[\\/]features[\\/]F-\d+\.ya?ml$/;
const ROOT_SPEC_PATH = /(^|[\\/])spec\.yaml$/;
const DONE_LINE = /^\s*status:\s*done\b/m;
const DONE_LINE_ALL = /^\s*status:\s*done\b/gm;

const DONE_BLOCK_REASON =
  'status: done is earned, not written — run `clad done <id>` (the strict gate flips it only when GREEN).';
const HASH_ID_REASON = 'hash ids only — use clad_create_feature';

function renderBlock(reason: string): string {
  return JSON.stringify({decision: 'block', reason});
}

function introducesDone(oldString: string, newString: string): boolean {
  return DONE_LINE.test(newString) && !DONE_LINE.test(oldString);
}

function countDoneLines(text: string): number {
  return text.match(DONE_LINE_ALL)?.length ?? 0;
}

/**
 * Decides whether a spec edit must be blocked. Two measured bypasses become
 * structurally impossible here (AC-2c2d29): hand-flipping `status: done`
 * (23 observed) and hand-authoring sequential F-NNN shard filenames. Every
 * other spec maintenance edit stays allowed (empty output).
 */
function resolvePreToolUseDecision(input: unknown, cwd: string): string {
  const rec = asRecord(input);
  const tool = asString(rec.tool_name);
  if (!WRITE_TOOLS.has(tool)) return '';
  const toolInput = asRecord(rec.tool_input);
  const filePath = asString(toolInput.file_path);
  if (filePath.length === 0) return '';
  // A Write that CREATES a sequential shard filename bypasses the hash-id
  // model (docs/spec-ids-multi-dev.md). Edits to legacy F-NNN files stay
  // allowed — they are stable historical identifiers, not new authorship.
  if (tool === 'Write' && SEQUENTIAL_SHARD_PATH.test(filePath)) {
    return renderBlock(HASH_ID_REASON);
  }
  if (!FEATURE_SHARD_PATH.test(filePath) && !ROOT_SPEC_PATH.test(filePath)) return '';
  if (tool === 'Edit') {
    return introducesDone(asString(toolInput.old_string), asString(toolInput.new_string))
      ? renderBlock(DONE_BLOCK_REASON)
      : '';
  }
  if (tool === 'MultiEdit') {
    const edits = Array.isArray(toolInput.edits) ? toolInput.edits : [];
    for (const e of edits) {
      const edit = asRecord(e);
      if (introducesDone(asString(edit.old_string), asString(edit.new_string))) {
        return renderBlock(DONE_BLOCK_REASON);
      }
    }
    return '';
  }
  // Write — block only when the content carries MORE `status: done` lines
  // than the current on-disk file: a brand-new done, not a faithful rewrite.
  const contentCount = countDoneLines(asString(toolInput.content));
  if (contentCount === 0) return '';
  let diskCount = 0;
  try {
    diskCount = countDoneLines(readFileSync(isAbsolute(filePath) ? filePath : join(cwd, filePath), 'utf8'));
  } catch {
    /* no prior file on disk → every done line in the content is new */
  }
  return contentCount > diskCount ? renderBlock(DONE_BLOCK_REASON) : '';
}

// --- Stop — deterministic trio with fingerprint-keyed demotion ----------

interface StopFailure {
  readonly detector: string;
  readonly path: string;
  readonly message: string;
}

function stopBlockPath(cwd: string): string {
  return join(cwd, '.cladding', 'stop-block.json');
}

/**
 * Runs the cheap deterministic trio (drift strict / arch / secret) silently
 * when the host fires Stop (AC-973837). Fresh failure fingerprints block with
 * the top findings + a `stop_blocked` event; an IDENTICAL fingerprint demotes
 * to allow so an unfixable-in-session failure never traps the user — the
 * SessionStart card resurfaces the persisted stop-block instead.
 */
function runStopGate(input: unknown, cwd: string): string {
  if (asRecord(input).stop_hook_active === true) return '';
  const failures: StopFailure[] = [];
  try {
    const drift = runDrift({strict: true, cwd});
    for (const f of drift.findings) {
      if (f.severity === 'error' || f.severity === 'warn') {
        failures.push({detector: f.detector, path: f.path ?? '', message: f.message});
      }
    }
  } catch {
    /* a broken stage must never brick the host — treat as no signal */
  }
  for (const [name, run] of [['ARCH', runArch], ['SECRET', runSecret]] as const) {
    try {
      const r = run({cwd});
      if (r.exitCode === 1) {
        const firstLine = (r.stderr ?? '').split('\n').find((l) => l.trim().length > 0);
        failures.push({detector: name, path: 'stage', message: firstLine ?? `${name.toLowerCase()} stage failed`});
      }
    } catch {
      /* same — silent degrade */
    }
  }
  const blockFile = stopBlockPath(cwd);
  if (failures.length === 0) {
    try {
      rmSync(blockFile, {force: true}); // resolved — clear the persisted block
    } catch {
      /* best-effort cleanup */
    }
    return '';
  }
  // Fingerprint = sha256 over the sorted detector|path set — state-keyed, so
  // the demotion can never be gamed by simply stopping repeatedly on NEW drift
  // (attempt-count demotion was rejected as a vacuous-green vector).
  const fingerprint = createHash('sha256')
    .update(failures.map((f) => `${f.detector}|${f.path}`).sort().join('\n'))
    .digest('hex');
  try {
    const prev = JSON.parse(readFileSync(blockFile, 'utf8')) as {fingerprint?: unknown};
    if (prev.fingerprint === fingerprint) return ''; // identical → demote; the SessionStart card resurfaces it
  } catch {
    /* no prior block recorded */
  }
  try {
    mkdirSync(dirname(blockFile), {recursive: true});
    writeFileSync(
      blockFile,
      `${JSON.stringify({fingerprint, count: failures.length, first: failures[0].detector})}\n`,
      'utf8',
    );
  } catch {
    /* unwritable state dir → still block; demotion just won't persist */
  }
  recordEvent(cwd, 'stop_blocked', {count: failures.length, fingerprint});
  const top = failures
    .slice(0, 2)
    .map((f) => `${f.detector}: ${truncate(f.message, 120)}`)
    .join('; ');
  return renderBlock(
    `cladding gate: ${failures.length} finding(s) — ${top}. Fix or stop again to dismiss (re-surfaced next session).`,
  );
}

// --- PostToolUse — debounced drift nudge --------------------------------

const DRIFT_DEBOUNCE_MS = 20_000;
const SOURCE_FILE_EXT = /\.(ts|js|py|rs|go)$/i;

function isWatchedSourcePath(filePath: string): boolean {
  if (filePath.length === 0) return false;
  if (/(^|[\\/])src[\\/]/.test(filePath)) return true;
  return SOURCE_FILE_EXT.test(filePath);
}

/**
 * After a source edit, runs the drift detectors silently (debounced via
 * `.cladding/hook-drift-ts`) and surfaces a one-line nudge ONLY when
 * error-severity findings exist — ambient feedback, never a block.
 */
function runPostToolUseDrift(input: unknown, cwd: string): string {
  const rec = asRecord(input);
  if (!WRITE_TOOLS.has(asString(rec.tool_name))) return '';
  const filePath = asString(asRecord(rec.tool_input).file_path);
  if (!isWatchedSourcePath(filePath)) return '';
  const stampPath = join(cwd, '.cladding', 'hook-drift-ts');
  const now = Date.now();
  try {
    const last = Number(readFileSync(stampPath, 'utf8').trim());
    if (Number.isFinite(last) && now - last < DRIFT_DEBOUNCE_MS) return '';
  } catch {
    /* no stamp yet → run */
  }
  try {
    mkdirSync(dirname(stampPath), {recursive: true});
    writeFileSync(stampPath, String(now), 'utf8');
  } catch {
    /* unwritable stamp → still run; worst case is an extra drift pass */
  }
  const report = runDrift({cwd});
  const errors = report.findings.filter((f) => f.severity === 'error');
  if (errors.length === 0) return '';
  return `cladding drift: ${errors.length} error(s) — ${errors[0].detector}: ${truncate(errors[0].message, 140)}`;
}

// --- dispatch + CLI wrapper ---------------------------------------------

/**
 * Handles one host hook event and returns the protocol output ('' = print
 * nothing / allow). Exported as a plain function so tests drive the protocol
 * without a host or a subprocess; never throws — an internal error degrades
 * to silence because a crashing hook must never brick the host session.
 */
export function runHookEvent(event: string, input: unknown, cwd: string): string {
  try {
    switch (event) {
      case 'SessionStart':
        return renderSessionStartCard(cwd);
      case 'UserPromptSubmit':
        return renderPromptSuggestion(input);
      case 'PreToolUse':
        return resolvePreToolUseDecision(input, cwd);
      case 'Stop':
        return runStopGate(input, cwd);
      case 'PostToolUse':
        return runPostToolUseDrift(input, cwd);
      default:
        return ''; // unknown event → allow; forward-compatible with new host events
    }
  } catch {
    return ''; // error-as-silence at the protocol boundary
  }
}

async function readStdin(): Promise<string> {
  if (process.stdin.isTTY) return '';
  let data = '';
  process.stdin.setEncoding('utf8');
  for await (const chunk of process.stdin) data += chunk;
  return data;
}

/**
 * Handler for `clad hook <event>` — reads the event payload from stdin
 * (empty/malformed → `{}`), prints the protocol output, and ALWAYS exits 0.
 */
export async function runHookCommand(event: string): Promise<void> {
  let out = '';
  try {
    const raw = await readStdin();
    let input: unknown = {};
    if (raw.trim().length > 0) {
      try {
        input = JSON.parse(raw);
      } catch {
        input = {};
      }
    }
    out = runHookEvent(event, input, '.');
  } catch {
    out = '';
  }
  if (out.length > 0) process.stdout.write(`${out}\n`);
  process.exit(0);
}
