// Cladding · context slice (F-d2c806)
//
// The personas have ordered agents to "dispatch the slice, never the whole
// spec" (Least Context) since the token-efficiency work — but no code ever
// produced the slice: pruneToFeature's only consumer was the benchmark.
// This is the first context-serving wiring. One call returns the working
// set for one feature: the focus feature in full, its transitive ancestors
// as summaries (orientation, not a spec dump), bound scenarios, the
// ai_hints patterns worth following, and the test_refs to run.

import {pruneToFeature} from './prune.js';
import type {Feature, Spec} from '../spec/types.js';

export interface ContextSlice {
  readonly focus: Feature;
  /** Transitive depends_on ancestors — title+status orientation only. */
  readonly ancestors: ReadonlyArray<{readonly id: string; readonly title: string; readonly status?: string}>;
  readonly scenarios: ReadonlyArray<{readonly id: string; readonly title: string}>;
  /** ai_hints.preferred_patterns — the project's standing instructions. */
  readonly preferred_patterns: ReadonlyArray<{readonly when: string; readonly prefer: string; readonly over?: string}>;
  /** Union of the focus feature's AC test_refs — what to run. */
  readonly test_refs: readonly string[];
}

export interface ContextLookupMiss {
  readonly not_found: string;
  readonly accepted_forms: readonly string[];
  readonly discovery: string;
}

/** id (F-…), slug, or module path → the feature, or null. */
function resolveFocus(spec: Spec, query: string): Feature | null {
  const features = spec.features ?? [];
  return (
    features.find((f) => f.id === query) ??
    features.find((f) => (f as {slug?: string}).slug === query) ??
    features.find((f) => (f.modules ?? []).includes(query)) ??
    null
  );
}

/**
 * Builds the deterministic context slice for a feature (stable ordering for
 * identical spec state — hosts can cache and diff it).
 */
export function buildContextSlice(spec: Spec, query: string): ContextSlice | ContextLookupMiss {
  const focus = resolveFocus(spec, query);
  if (!focus) {
    return {
      not_found: query,
      accepted_forms: ['feature id (F-…)', 'slug', 'module path (e.g. src/auth/login.ts)'],
      discovery: 'grep spec/index.yaml — one line per feature (id, slug, status), regenerated by clad sync',
    };
  }
  const pruned = pruneToFeature(spec, focus.id);
  const ancestors = (pruned.features ?? [])
    .filter((f) => f.id !== focus.id)
    .map((f) => ({id: f.id, title: f.title, status: f.status}))
    .sort((a, b) => a.id.localeCompare(b.id));
  const scenarios = (pruned.scenarios ?? [])
    .map((s) => ({id: s.id, title: s.title}))
    .sort((a, b) => a.id.localeCompare(b.id));
  const preferred = (spec.project?.ai_hints?.preferred_patterns ?? []).map((p) => ({
    when: p.when,
    prefer: p.prefer,
    ...(p.over !== undefined ? {over: p.over} : {}),
  }));
  const testRefs = [
    ...new Set((focus.acceptance_criteria ?? []).flatMap((ac) => ac.test_refs ?? [])),
  ].sort();
  return {focus, ancestors, scenarios, preferred_patterns: preferred, test_refs: testRefs};
}
