#!/usr/bin/env python3
"""A/B benchmark — English-canonical spec (B) vs Korean-canonical spec (A).

Measures the recurring token cost of the canonical spec surface that the model
re-reads on every session (project-context.md + capabilities + scenario flows),
in Korean vs the equivalent English, and projects the money saved.

Token counts use tiktoken cl100k_base as a PROXY for Claude's tokenizer. Claude
is typically *more* token-heavy for Korean than cl100k, so the savings reported
here are conservative (real savings are at least this large).

No API key is required — this is a deterministic measurement over fixed,
faithful EN/KO equivalents under scripts/i18n-ab/.

Run:  /path/to/venv/bin/python3 scripts/bench-i18n.py
"""
from __future__ import annotations

import pathlib

import tiktoken

ROOT = pathlib.Path(__file__).resolve().parent
EN = ROOT / "i18n-ab" / "canonical-en.md"
KO = ROOT / "i18n-ab" / "canonical-ko.md"
REPORT = ROOT.parent / "docs" / "i18n-ab-report.md"

# Illustrative input/output prices (USD per 1M tokens). Clearly labeled as
# illustrative in the report — relative savings are what matter.
PRICES = {
    "Opus 4.x":   {"in": 15.0, "out": 75.0},
    "Sonnet 4.x": {"in": 3.0,  "out": 15.0},
    "Haiku 4.5":  {"in": 1.0,  "out": 5.0},
}
READ_PROJECTIONS = [1, 50, 200, 1000]


def main() -> int:
    enc = tiktoken.get_encoding("cl100k_base")
    en_text, ko_text = EN.read_text(), KO.read_text()
    en_tok, ko_tok = len(enc.encode(en_text)), len(enc.encode(ko_text))
    saved = ko_tok - en_tok
    ratio = ko_tok / en_tok
    reduction = saved / ko_tok

    lines: list[str] = []
    add = lines.append
    add("# i18n A/B — English-canonical spec (B) vs Korean-canonical (A)\n")
    add("> Generated by `scripts/bench-i18n.py` · tokens via tiktoken cl100k_base "
        "(proxy for Claude;\n> Claude is heavier on Korean, so savings here are "
        "**conservative**).\n")
    add("> Payload = the canonical spec the model RE-READS every session "
        "(project-context + capabilities + scenario flows), under "
        "`scripts/i18n-ab/`.\n")

    add("## 1. Token count (one read of the canonical surface)\n")
    add("| group | canonical lang | tokens | chars |")
    add("|---|---|---|---|")
    add(f"| A (baseline) | Korean | {ko_tok} | {len(ko_text)} |")
    add(f"| B (this change) | English | {en_tok} | {len(en_text)} |")
    add("")
    add(f"- **Korean is {ratio:.2f}x the tokens of the equivalent English** "
        f"({ko_tok} vs {en_tok}).")
    add(f"- **Per read: {saved} tokens saved ({reduction*100:.1f}% fewer)** with B.\n")

    add("## 2. Cost — recurring (the canonical spec is re-read every session)\n")
    add("Illustrative input prices (USD / 1M tokens): "
        + ", ".join(f"{m} ${p['in']}" for m, p in PRICES.items()) + ".\n")
    add("| model | reads | A (Korean) $ | B (English) $ | saved $ | saved % |")
    add("|---|---|---|---|---|---|")
    for model in ("Opus 4.x", "Sonnet 4.x"):
        rate = PRICES[model]["in"] / 1_000_000
        for n in READ_PROJECTIONS:
            a = ko_tok * n * rate
            b = en_tok * n * rate
            add(f"| {model} | {n} | ${a:,.4f} | ${b:,.4f} | ${a-b:,.4f} | "
                f"{reduction*100:.0f}% |")
    add("")

    # One-time cost of generating the Korean human view via Haiku
    # (input ≈ the English doc, output ≈ the Korean translation).
    h = PRICES["Haiku 4.5"]
    view_cost = (en_tok * h["in"] + ko_tok * h["out"]) / 1_000_000
    add("## 3. One-time cost of the Korean companion view (B)\n")
    add(f"- Generating `docs/project-context.ko.md` once via Haiku 4.5 "
        f"≈ **${view_cost:.5f}** (input {en_tok} + output {ko_tok} tokens).")
    add("- It is human-only — never sent to the model — so it adds **$0 per "
        "session**.\n")

    add("## 4. Break-even (when B's one-time view cost pays for itself)\n")
    add("| model | saved $/read | reads to break even |")
    add("|---|---|---|")
    for model in ("Opus 4.x", "Sonnet 4.x"):
        rate = PRICES[model]["in"] / 1_000_000
        per_read = (ko_tok - en_tok) * rate
        be = view_cost / per_read if per_read > 0 else float("inf")
        add(f"| {model} | ${per_read:.6f} | {be:.1f} reads |")
    add("")

    add("## 5. Verdict\n")
    add(f"- **Cost:** B cuts the recurring per-read spend on the canonical spec by "
        f"**~{reduction*100:.0f}%** ({saved} tokens/read). The saving recurs on "
        f"every session/feature dispatch — it is not one-time.")
    add("- **Performance:** fewer input tokens per dispatch → proportionally lower "
        "input cost and faster time-to-first-token. The only added work is a "
        "one-time Haiku translation at init/refine (human view), which the model "
        "never reads.")
    add("- **결과물 (output):** the English canonical is the SSoT the model reads; "
        "`docs/project-context.ko.md` is a faithful human view (see the fixtures "
        "in `scripts/i18n-ab/`). Same meaning, fewer machine-read tokens.")
    add("- **Caveat:** tiktoken proxy + fixed representative fixtures (no API key "
        "in this run). Claude's Korean tokenization is heavier, so real savings "
        "are at least those shown.\n")

    report = "\n".join(lines)
    REPORT.write_text(report)
    print(report)
    print(f"\n[wrote] {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
