// Cladding · plugin asset builder (v0.3.1 → v0.4.x, F-076 · F-077 · F-081).
//
// Single source of truth: src/agents/*.md (personas) + skills/*/SKILL.md
// (verbs). This script generates the host-specific plugin layouts:
//
//   Claude Code (plugins/claude-code/, v0.4.0):
//     agents/<id>.md       ← src/agents/<id>.md (verbatim copy)
//     commands/init.md     ← skills/init/SKILL.md (single user-facing verb)
//     .claude-plugin/plugin.json — declares mcpServers.cladding (canonical
//       MCP server declaration; replaces the v0.3.x repo-root `.mcp.json`).
//
//   Codex (plugins/codex/, v0.3.2, F-077):
//     skills/<verb>/SKILL.md   ← copied from repo-root skills/<verb>/SKILL.md
//     skills/<persona>/SKILL.md ← src/agents/<persona>.md re-wrapped as SKILL.md
//     .mcp.json             ← already authored under plugins/codex/
//     .codex-plugin/plugin.json ← already authored
//
//   Gemini CLI (plugins/gemini-cli/, v0.3.6, F-081):
//     commands/<verb>.toml ← transpiled from repo-root skills/<verb>/SKILL.md
//                            (frontmatter.description → toml `description`,
//                             body → toml `prompt` as a literal multi-line)
//     gemini-extension.json + GEMINI.md already authored.
//
// The src side stays canonical — every loadPersona() call in the
// runtime reads from src/agents. The drift detector enforces lockstep.
//
// Run: `npm run build:plugin` or as part of `npm run build`.

import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import {join} from 'node:path';

import {parse as parseYaml} from 'yaml';

const SRC_AGENTS = 'src/agents';
const SRC_SKILLS = 'skills';
const SRC_DETECTORS = 'src/stages/detectors';
const CLAUDE_PLUGIN_DIR = 'plugins/claude-code';
const CLAUDE_PLUGIN_JSON = `${CLAUDE_PLUGIN_DIR}/.claude-plugin/plugin.json`;

// --- Phase A — Claude Code mirror (plugins/claude-code/agents/) -------

const CLAUDE_AGENTS = `${CLAUDE_PLUGIN_DIR}/agents`;
mkdirSync(CLAUDE_AGENTS, {recursive: true});

// Canonical persona file list — used to copy AND to sweep stale mirror files
// from earlier builds (e.g. the pre-0.6.0 `librarian.md` / `specialists.md`,
// renamed to planner/developer). A mirror must track src/agents exactly.
const personaFiles = readdirSync(SRC_AGENTS).filter(
  (f) => f.endsWith('.md') && f !== 'README.md' && statSync(join(SRC_AGENTS, f)).isFile(),
);

const claudeGenerated = [];
for (const entry of personaFiles) {
  copyFileSync(join(SRC_AGENTS, entry), join(CLAUDE_AGENTS, entry));
  claudeGenerated.push(entry);
}
for (const file of readdirSync(CLAUDE_AGENTS)) {
  if (!file.endsWith('.md') || file === 'README.md') continue;
  if (!personaFiles.includes(file)) rmSync(join(CLAUDE_AGENTS, file));
}
writeFileSync(
  join(CLAUDE_AGENTS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding plugin · agents/\n' +
    '\n' +
    'This directory is the Claude Code plugin manifest mirror of `src/agents/`.\n' +
    'Files here are copied verbatim from `src/agents/` by\n' +
    '`scripts/build-plugin.mjs` (run by `npm run build:plugin`).\n' +
    '\n' +
    'Edit the source under `src/agents/<id>.md`, then re-run the build.\n',
);
console.log(`cladding plugin · claude-code: copied ${claudeGenerated.length} agents → ${CLAUDE_AGENTS}/`);

// v0.4.0 (F-80d19d): Claude Code commands = `init` only (user-facing slash).
// Other verbs are invoked by the AI via natural language → `clad <verb>` CLI;
// keeping them out of the slash auto-complete keeps the namespace clean.
const CLAUDE_COMMANDS = `${CLAUDE_PLUGIN_DIR}/commands`;
mkdirSync(CLAUDE_COMMANDS, {recursive: true});
const initSkill = join(SRC_SKILLS, 'init', 'SKILL.md');
try {
  statSync(initSkill);
  copyFileSync(initSkill, join(CLAUDE_COMMANDS, 'init.md'));
  // Sweep stale per-verb commands from earlier builds (verb.md files and the
  // legacy clad.md wrapper).
  for (const file of readdirSync(CLAUDE_COMMANDS)) {
    if (file === 'init.md') continue;
    if (!file.endsWith('.md')) continue;
    rmSync(join(CLAUDE_COMMANDS, file));
  }
  console.log(`cladding plugin · claude-code: generated init slash command → ${CLAUDE_COMMANDS}/init.md`);
} catch {
  // skills/init/SKILL.md missing — leave the commands dir untouched and log
  // a warning so the build still completes for partial source trees.
  console.warn(`cladding plugin · claude-code: ${initSkill} not found — slash command skipped`);
}

// --- Phase A2 — Claude Code self-contained engine (v0.5.2) ------------
//
// The marketplace plugin is git-distributed (marketplace.json
// `source: "./plugins/claude-code"`), so for its MCP server to launch
// WITHOUT a global `clad` on PATH we ship the built engine alongside it.
// plugin.json wires `command: node, args: [${CLAUDE_PLUGIN_ROOT}/dist/clad.js,
// serve]` (inline mcpServers — the reliable spot for ${CLAUDE_PLUGIN_ROOT}
// expansion, side-stepping the .mcp.json expansion bug, claude-code#9427).
//
// build.mjs runs before this script under `npm run build`, so dist/clad.js +
// dist/schema.json + dist/agents/ already exist. The bundle is committed
// (same model as the agent mirrors above) because the git source IS what users
// install. Only the Claude Code lane is bundled — Codex/Gemini do not expand
// ${CLAUDE_PLUGIN_ROOT}, so they keep the global `clad` command.
const CLAUDE_DIST = `${CLAUDE_PLUGIN_DIR}/dist`;
if (existsSync('dist/clad.js')) {
  mkdirSync(`${CLAUDE_DIST}/agents`, {recursive: true});
  copyFileSync('dist/clad.js', `${CLAUDE_DIST}/clad.js`);
  chmodSync(`${CLAUDE_DIST}/clad.js`, 0o755);
  copyFileSync('dist/schema.json', `${CLAUDE_DIST}/schema.json`);
  let bundledPersonas = 0;
  for (const f of readdirSync('dist/agents')) {
    if (!f.endsWith('.md')) continue;
    copyFileSync(`dist/agents/${f}`, `${CLAUDE_DIST}/agents/${f}`);
    bundledPersonas++;
  }
  // Sweep personas that no longer exist in dist/agents (0.6.0 renames).
  const distPersonas = readdirSync('dist/agents').filter((f) => f.endsWith('.md'));
  for (const f of readdirSync(`${CLAUDE_DIST}/agents`)) {
    if (f.endsWith('.md') && !distPersonas.includes(f)) rmSync(`${CLAUDE_DIST}/agents/${f}`);
  }
  console.log(
    `cladding plugin · claude-code: bundled engine (clad.js + schema.json + ${bundledPersonas} personas) → ${CLAUDE_DIST}/`,
  );
} else {
  console.warn(
    'cladding plugin · claude-code: dist/clad.js absent — run `npm run build` (build.mjs first) to bundle the standalone engine',
  );
}

// --- Phase A3 — Claude Code hooks wiring guard (v0.6.0, F-1d23a6) ------
//
// plugins/claude-code/hooks/hooks.json is CANONICAL (hand-authored in the
// plugin dir, not generated) — this script never writes or sweeps it. The
// guard only validates presence + JSON shape so a refactor of the sweep
// logic above (or a bad merge) cannot silently ship the plugin without its
// lifecycle wiring. tests/scripts/hooks-config.test.ts pins the full shape.

const CLAUDE_HOOKS_JSON = `${CLAUDE_PLUGIN_DIR}/hooks/hooks.json`;
try {
  const hooksDoc = JSON.parse(readFileSync(CLAUDE_HOOKS_JSON, 'utf8'));
  const hookEvents = Object.keys(hooksDoc.hooks ?? {});
  if (hookEvents.length === 0) throw new Error('no events wired under "hooks"');
  console.log(
    `cladding plugin · claude-code: hooks wiring OK (${hookEvents.length} events) — ${CLAUDE_HOOKS_JSON}`,
  );
} catch (err) {
  console.warn(
    `cladding plugin · claude-code: WARN ${CLAUDE_HOOKS_JSON} missing/invalid (${err.message}) — lifecycle hooks will not fire`,
  );
}

// --- Phase B — Codex mirror (plugins/codex/skills/) -------------------

const CODEX_SKILLS = 'plugins/codex/skills';
mkdirSync(CODEX_SKILLS, {recursive: true});

// 1) verb skills — copied verbatim from repo-root `skills/<verb>/SKILL.md`
let codexVerbCount = 0;
for (const verb of readdirSync(SRC_SKILLS)) {
  const srcDir = join(SRC_SKILLS, verb);
  if (!statSync(srcDir).isDirectory()) continue;
  const srcFile = join(srcDir, 'SKILL.md');
  try {
    statSync(srcFile);
  } catch {
    continue;
  }
  const dstDir = join(CODEX_SKILLS, verb);
  mkdirSync(dstDir, {recursive: true});
  copyFileSync(srcFile, join(dstDir, 'SKILL.md'));
  codexVerbCount++;
}

// 2) persona skills — re-wrap src/agents/<id>.md as Codex SKILL.md
// The persona files already use YAML frontmatter with name + description
// + tools + capabilities; Codex's SKILL.md spec accepts arbitrary
// frontmatter and only requires `description`. The verbatim copy
// satisfies that — no transformation needed for v0.3.2.
let codexPersonaCount = 0;
for (const entry of readdirSync(SRC_AGENTS)) {
  if (!entry.endsWith('.md')) continue;
  if (entry === 'README.md') continue;
  const src = join(SRC_AGENTS, entry);
  if (!statSync(src).isFile()) continue;
  const personaId = entry.replace(/\.md$/, '');
  const dstDir = join(CODEX_SKILLS, personaId);
  mkdirSync(dstDir, {recursive: true});
  // Read + re-emit so we can confirm the YAML frontmatter has a
  // `description` field (Codex requires it). For v0.3.2 we trust the
  // src/agents files; if a future agent lacks description, the build
  // logs a warning and copies anyway.
  const content = readFileSync(src, 'utf8');
  if (!/^---\n[\s\S]*?\ndescription:/m.test(content)) {
    console.warn(`cladding plugin · codex: ${entry} lacks 'description' frontmatter — Codex may reject the skill.`);
  }
  writeFileSync(join(dstDir, 'SKILL.md'), content);
  codexPersonaCount++;
}

// 3) sweep stale skill dirs from earlier builds — anything that is neither a
// current verb skill nor a current persona (e.g. the removed `work` verb, the
// pre-0.6.0 `librarian`/`specialists` persona dirs). The mirror must track
// the two canonical sources exactly.
const codexExpected = new Set([
  ...readdirSync(SRC_SKILLS).filter((v) => {
    try {
      return statSync(join(SRC_SKILLS, v, 'SKILL.md')).isFile();
    } catch {
      return false;
    }
  }),
  ...personaFiles.map((f) => f.replace(/\.md$/, '')),
]);
for (const entry of readdirSync(CODEX_SKILLS)) {
  const full = join(CODEX_SKILLS, entry);
  if (!statSync(full).isDirectory()) continue;
  if (!codexExpected.has(entry)) rmSync(full, {recursive: true});
}

writeFileSync(
  join(CODEX_SKILLS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit src/agents/<id>.md or skills/<verb>/SKILL.md instead. -->\n' +
    '\n' +
    '# Cladding Codex plugin · skills/\n' +
    '\n' +
    'This directory is the Codex plugin manifest mirror, generated from\n' +
    'two canonical sources by `scripts/build-plugin.mjs`:\n' +
    '\n' +
    '- `<verb>/SKILL.md` ← copied verbatim from repo-root `skills/<verb>/SKILL.md`\n' +
    '- `<persona>/SKILL.md` ← copied verbatim from `src/agents/<persona>.md`\n' +
    '\n' +
    'Re-run `npm run build:plugin` after editing either source.\n',
);
console.log(
  `cladding plugin · codex: copied ${codexVerbCount} verbs + ${codexPersonaCount} personas → ${CODEX_SKILLS}/`,
);

// --- Phase C — Gemini CLI mirror (plugins/gemini-cli/commands/) -------

const GEMINI_COMMANDS = 'plugins/gemini-cli/commands';
mkdirSync(GEMINI_COMMANDS, {recursive: true});

/**
 * Splits a SKILL.md into its YAML frontmatter object and the body.
 * Returns null when no frontmatter delimiter is present so the
 * caller can decide whether to warn or skip.
 */
function splitFrontmatter(raw) {
  if (!raw.startsWith('---\n')) return null;
  const end = raw.indexOf('\n---\n', 4);
  if (end === -1) return null;
  const yamlText = raw.slice(4, end);
  const body = raw.slice(end + 5);
  return {frontmatter: parseYaml(yamlText) ?? {}, body};
}

/**
 * Escapes a string for TOML basic-string syntax (`"..."`).
 * - `\` → `\\`
 * - `"` → `\"`
 * Apostrophes pass through. Control chars are NOT scrubbed; cladding
 * skill descriptions are author-controlled prose and never contain
 * them in practice.
 */
function escapeTomlBasic(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Renders a SKILL.md description + body into a TOML file Gemini CLI
 * accepts. Strategy:
 * - `description = "<escaped-basic-string>"` — single-line value.
 * - `prompt = '''<literal-multi-line>'''` — literal multi-line so
 *   backticks, backslashes, and other markdown punctuation pass
 *   through unaltered. The only escape concern is `'''` inside the
 *   body itself; we detect that case and fall back to the basic
 *   multi-line form (`"""..."""`) with appropriate escapes.
 */
function renderToml(description, body) {
  const desc = `description = "${escapeTomlBasic(description)}"`;
  if (!body.includes("'''")) {
    // Trim trailing whitespace but keep a leading newline for
    // readability — the closing `'''` lands on its own line.
    const trimmed = body.replace(/\s+$/, '');
    return `${desc}\nprompt = '''\n${trimmed}\n'''\n`;
  }
  // Fallback: body contains the literal sequence ' x 3, so use the
  // basic multi-line form and escape backslashes + double quotes.
  const escaped = body.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\s+$/, '');
  return `${desc}\nprompt = """\n${escaped}\n"""\n`;
}

// v0.4.0 (F-80d19d): slash command 노출 = `init` 만. 다른 verb 는 AI 가
// 자연어로 인식해 `clad <verb>` CLI 를 직접 호출하므로 사용자가 slash
// auto-complete 에서 직접 볼 필요 없음. Codex skills 는 AI 자동 invoke
// 라 12 verb 유지 (Phase B 그대로).
const USER_FACING_VERBS = new Set(['init']);

let geminiVerbCount = 0;
const geminiWarnings = [];
for (const verb of readdirSync(SRC_SKILLS)) {
  if (!USER_FACING_VERBS.has(verb)) continue;
  const srcDir = join(SRC_SKILLS, verb);
  if (!statSync(srcDir).isDirectory()) continue;
  const srcFile = join(srcDir, 'SKILL.md');
  try {
    statSync(srcFile);
  } catch {
    continue;
  }
  const raw = readFileSync(srcFile, 'utf8');
  const split = splitFrontmatter(raw);
  if (!split) {
    geminiWarnings.push(`${srcFile}: no YAML frontmatter — skipped`);
    continue;
  }
  const description = String(split.frontmatter.description ?? '').trim();
  if (!description) {
    geminiWarnings.push(`${srcFile}: frontmatter has no description field — skipped`);
    continue;
  }
  const body = split.body.trimStart();
  const toml = renderToml(description, body);
  writeFileSync(join(GEMINI_COMMANDS, `${verb}.toml`), toml);
  geminiVerbCount++;
}

// Clean up any stale verb .toml files from earlier builds (when all 12 verbs
// were emitted). Only the verbs in USER_FACING_VERBS should remain.
for (const file of readdirSync(GEMINI_COMMANDS)) {
  if (!file.endsWith('.toml')) continue;
  const verb = file.replace(/\.toml$/, '');
  if (USER_FACING_VERBS.has(verb)) continue;
  rmSync(join(GEMINI_COMMANDS, file));
}

// AUTO-GENERATED sentinel — same pattern the Claude Code mirror uses.
writeFileSync(
  join(GEMINI_COMMANDS, 'README.md'),
  '<!-- AUTO-GENERATED by scripts/build-plugin.mjs — do not edit. -->\n' +
    '<!-- Edit skills/<verb>/SKILL.md (the canonical source) instead. -->\n' +
    '\n' +
    '# Cladding Gemini CLI plugin · commands/\n' +
    '\n' +
    'This directory is the Gemini CLI plugin manifest mirror, generated\n' +
    'by `scripts/build-plugin.mjs` from `skills/<verb>/SKILL.md`:\n' +
    '\n' +
    '- `description` ← SKILL.md frontmatter `description`\n' +
    '- `prompt` ← SKILL.md body (after frontmatter)\n' +
    '\n' +
    'TOML output uses literal multi-line strings (`\'\'\'…\'\'\'`) so\n' +
    'backticks and backslashes pass through unaltered.\n' +
    '\n' +
    'Re-run `npm run build:plugin` after editing the source.\n',
);

for (const w of geminiWarnings) {
  console.warn(`cladding plugin · gemini-cli: WARN ${w}`);
}
console.log(`cladding plugin · gemini-cli: transpiled ${geminiVerbCount} verbs → ${GEMINI_COMMANDS}/`);

// --- Phase D — Detector count auto-recompute (v0.3.17, F-092) ---------
//
// HARNESS_INTEGRITY detects drift between the count of non-index files
// under src/stages/detectors/ and the `N/M` value declared in
// .claude-plugin/plugin.json `ironclad.current.detectors` (and `.target`).
// Two concurrent branches each adding +1 detector merge cleanly on the
// file side but silently leave `(N+1)/(N+1)` instead of `(N+2)/(N+2)`
// because manual edits don't compose.
//
// This phase recomputes the count from the filesystem (the single
// source of truth) and rewrites both `current.detectors` and
// `target.detectors`. The build is idempotent — re-running with no
// changes produces no diff.
//
// Rewriting preserves byte layout: rather than parsing + reserializing
// the JSON (which would normalize formatting and produce nuisance
// diffs), the script targets just the two scalar fields by regex on
// the surrounding lines. The values are always `"N/M"` strings, so the
// pattern is tight.

function countDetectorFiles() {
  // Exclude the registry (index.ts) and shared helpers (with-spec.ts):
  // they live alongside detectors but are not themselves detectors.
  return readdirSync(SRC_DETECTORS).filter(
    (f) => f.endsWith('.ts') && f !== 'index.ts' && f !== 'with-spec.ts',
  ).length;
}

function rewriteDetectorCount(jsonPath, count) {
  const original = readFileSync(jsonPath, 'utf8');
  const want = `"${count}/${count}"`;
  // Two replacements anchored to the parent key — `target.detectors`
  // and `current.detectors`. `[\s\S]*?` is lazy so it captures the
  // shortest run from the parent's `{` to the first `"detectors":`
  // inside it. Any future `"detectors":` key under a different parent
  // (e.g. a hypothetical `stages.detectors`) is untouched because the
  // match anchor still requires `"target"` or `"current"`.
  let updated = original.replace(
    /("target":\s*\{[\s\S]*?"detectors":\s*)"\d+\/\d+"/,
    `$1${want}`,
  );
  updated = updated.replace(
    /("current":\s*\{[\s\S]*?"detectors":\s*)"\d+\/\d+"/,
    `$1${want}`,
  );
  if (updated === original) return {changed: false, count};
  writeFileSync(jsonPath, updated);
  return {changed: true, count};
}

const detectorCount = countDetectorFiles();
const claudeResult = rewriteDetectorCount(CLAUDE_PLUGIN_JSON, detectorCount);
if (claudeResult.changed) {
  console.log(
    `cladding plugin · detectors: recomputed → ${detectorCount}/${detectorCount} (updated ${CLAUDE_PLUGIN_JSON})`,
  );
} else {
  console.log(
    `cladding plugin · detectors: ${detectorCount}/${detectorCount} (already in sync)`,
  );
}

// --- Phase E — stages-implemented auto-derive (v0.6.2) ----------------
//
// Same rationale as Phase D: the Claude Code manifest's `stages-implemented`
// array must mirror what the engine actually runs (TIER_STAGES.all in
// src/cli/clad.ts). Hand-maintained it silently drifted (13 listed vs 15
// run) and HARNESS_INTEGRITY's stage-list check now guards it — so derive it
// here from the one canonical source (source TEXT, not import, to match the
// detector's anti-circular constraint) and rewrite the array. Idempotent.

function deriveStageList(cliSource) {
  const m = cliSource.match(/TIER_STAGES[\s\S]*?\ball:\s*\[([^\]]*)\]/);
  if (!m) return null;
  return [...m[1].matchAll(/['"]([^'"]+)['"]/g)].map((x) => x[1]);
}

function rewriteStageList(jsonPath, stages) {
  const original = readFileSync(jsonPath, 'utf8');
  const want = `[${stages.map((s) => `"${s}"`).join(', ')}]`;
  const updated = original.replace(/("stages-implemented":\s*)\[[^\]]*\]/, `$1${want}`);
  if (updated === original) return {changed: false};
  writeFileSync(jsonPath, updated);
  return {changed: true};
}

const CLI_SOURCE = 'src/cli/clad.ts';
if (existsSync(CLI_SOURCE)) {
  const stages = deriveStageList(readFileSync(CLI_SOURCE, 'utf8'));
  if (stages && stages.length > 0) {
    const stageResult = rewriteStageList(CLAUDE_PLUGIN_JSON, stages);
    console.log(
      stageResult.changed
        ? `cladding plugin · stages: re-derived → ${stages.length} stages (updated ${CLAUDE_PLUGIN_JSON})`
        : `cladding plugin · stages: ${stages.length} stages (already in sync)`,
    );
  } else {
    console.warn(
      `cladding plugin · stages: could not parse TIER_STAGES.all from ${CLI_SOURCE} — array left as-is`,
    );
  }
}
