// Cladding · scenarios · ab · report (v0.3.47, F-4db939)
//
// Deterministic markdown generation from A/B snapshots. The same
// snapshot inputs always produce the same markdown — committed
// reports live under docs/ab-evaluation/ and act as a snapshot test.
// A regression that changes the metric numbers will diff against the
// committed report and fail the test, forcing reviewer attention.

import {readFileSync, writeFileSync, existsSync, mkdirSync} from 'node:fs';
import {dirname} from 'node:path';

import {diffToRows, type AbSnapshot} from './_ab-metrics.js';
import type {DriftCatchResult} from './_drift-injection.js';
import type {QueryAnswer} from './_query-bench.js';

/** Optional outcome-quality bundle (F-ba2e05). */
export interface OutcomeReportInput {
  /** 4 drift scenarios × 2 groups = 8 results, in DI-1…DI-4 / A,B order. */
  readonly driftResults: readonly DriftCatchResult[];
  /** 5 queries × 2 groups = 10 answers, in Q1…Q5 / A,B order. */
  readonly queryResults: ReadonlyMap<'A' | 'B', readonly QueryAnswer[]>;
}

/** Case report top-level options. */
export interface CaseReportInput {
  readonly caseTitle: string;
  readonly intent: string;
  readonly description: string;
  readonly hypothesisFocus: readonly string[];
  readonly m1A: AbSnapshot;
  readonly m1B: AbSnapshot;
  readonly m2A: AbSnapshot;
  readonly m2B: AbSnapshot;
  readonly outcome?: OutcomeReportInput;
}

export function renderCaseReport(input: CaseReportInput): string {
  const lines: string[] = [];
  lines.push(
    `<!-- Cladding · ab-evaluation · ${input.caseTitle} · auto-generated by tests/scenarios/ab/case-*.test.ts -->`,
  );
  lines.push('');
  lines.push(`# A/B Evaluation: ${input.caseTitle}`);
  lines.push('');
  lines.push(
    '_Snapshot note (2026-07-05): detector count was 25 at this run; the suite has since grown to 41 (0.8.x). Body preserved as an append-only snapshot._',
  );
  lines.push('');
  lines.push(`**Intent:** \`${input.intent}\``);
  lines.push('');
  lines.push(input.description.trim());
  lines.push('');
  lines.push('## Hypotheses tested');
  lines.push('');
  for (const h of input.hypothesisFocus) lines.push(`- ${h}`);
  lines.push('');

  // M1
  lines.push('## M1 — Initial setup');
  lines.push('');
  lines.push(renderMilestoneTable(input.m1A, input.m1B));
  lines.push('');
  lines.push(renderDetectorBlock(input.m1A, input.m1B));
  lines.push('');

  // M2
  lines.push('## M2 — First feature complete');
  lines.push('');
  lines.push(renderMilestoneTable(input.m2A, input.m2B));
  lines.push('');
  lines.push(renderDetectorBlock(input.m2A, input.m2B));
  lines.push('');

  // Findings
  lines.push('## Findings');
  lines.push('');
  lines.push(renderFindings(input.m2A, input.m2B));
  lines.push('');

  // Outcome quality (optional, F-ba2e05)
  if (input.outcome) {
    lines.push('## Outcome Quality (F-ba2e05)');
    lines.push('');
    lines.push(renderOutcomeSection(input.outcome));
    lines.push('');
  }

  // Replay
  lines.push('## How to reproduce');
  lines.push('');
  lines.push('```bash');
  lines.push(`npm test -- tests/scenarios/ab/case-${slugify(input.caseTitle)}.test.ts`);
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

function renderMilestoneTable(a: AbSnapshot, b: AbSnapshot): string {
  const rows = diffToRows(a, b);
  const out: string[] = [];
  out.push('| Metric | A (Cladding) | B (Vanilla) | Δ |');
  out.push('|---|---:|---:|---:|');
  for (const r of rows) {
    out.push(`| ${escapePipe(r.label)} | ${r.a} | ${r.b} | ${r.delta} |`);
  }
  return out.join('\n');
}

function renderDetectorBlock(a: AbSnapshot, b: AbSnapshot): string {
  const lines: string[] = [];
  lines.push('**Detector outcomes** (META_INTEGRITY + HARDCODED_SECRET excluded — toolchain-only checks):');
  lines.push('');
  lines.push('```');
  lines.push(`A (Cladding) — errors: ${a.crossDocConsistency.errors}  warns: ${a.crossDocConsistency.warnings}  infos: ${a.crossDocConsistency.infos}`);
  if (a.crossDocConsistency.errorSamples.length > 0) {
    lines.push('  Sample errors:');
    for (const s of a.crossDocConsistency.errorSamples) lines.push(`    - ${truncate(s, 140)}`);
  }
  lines.push('');
  lines.push(`B (Vanilla)  — errors: ${b.crossDocConsistency.errors}  warns: ${b.crossDocConsistency.warnings}  infos: ${b.crossDocConsistency.infos}`);
  if (b.crossDocConsistency.errorSamples.length > 0) {
    lines.push('  Sample errors:');
    for (const s of b.crossDocConsistency.errorSamples) lines.push(`    - ${truncate(s, 140)}`);
  }
  lines.push('```');
  return lines.join('\n');
}

function renderFindings(a: AbSnapshot, b: AbSnapshot): string {
  const lines: string[] = [];
  const tieredA =
    a.tieredArtifactCount.tierA + a.tieredArtifactCount.tierB + a.tieredArtifactCount.tierC + a.tieredArtifactCount.tierD;
  const tieredB =
    b.tieredArtifactCount.tierA + b.tieredArtifactCount.tierB + b.tieredArtifactCount.tierC + b.tieredArtifactCount.tierD;
  lines.push(
    `- **Structured artifacts**: cladding produces ${tieredA} tier-banner-bearing files vs vanilla's ${tieredB}.`,
  );
  lines.push(
    `- **Spec ↔ code traceability**: cladding emits ${a.specCompleteness.features} feature(s), ${a.specCompleteness.acceptanceCriteria} AC(s), ${a.specCompleteness.scenarios} scenario(s), ${a.specCompleteness.capabilities} capability(s); vanilla has 0 of each.`,
  );
  lines.push(
    `- **Architecture enforcement**: cladding declares ${a.layerCompliance.layersDeclared} layer(s) with ${a.layerCompliance.forbiddenImportRules} forbidden-import rule(s); vanilla has 0.`,
  );
  lines.push(
    `- **Detector behavior**: cladding-managed tree → ${a.crossDocConsistency.errors} error(s) / ${a.crossDocConsistency.warnings} warn(s) / ${a.crossDocConsistency.infos} info(s). Vanilla tree → ${b.crossDocConsistency.errors} / ${b.crossDocConsistency.warnings} / ${b.crossDocConsistency.infos}. The detectors that gate against spec (REFERENCE_INTEGRITY, MISSING_IMPLEMENTATION, ARCHITECTURE_FROM_SPEC, CAPABILITIES_FEATURE_MAPPING) need cladding's artifacts to evaluate — without them they silently pass. The "0 errors on vanilla" therefore is **absence of signal**, not absence of drift.`,
  );
  lines.push(
    `- **Token cost**: cladding's cumulative artifact + code consumes ~${a.tokenConsumption.estTokens} tokens vs vanilla's ~${b.tokenConsumption.estTokens} (heuristic chars/4) — Δ ≈ ${a.tokenConsumption.estTokens - b.tokenConsumption.estTokens} tokens, the price of structure.`,
  );
  lines.push(
    `- **Code surface**: vanilla writes ${b.codeStructure.sourceFiles} source file(s) / ${b.codeStructure.totalSourceLoc} LoC + ${b.codeStructure.testFiles} test file(s) / ${b.testCoverage.testCases} test case(s); cladding writes ${a.codeStructure.sourceFiles} / ${a.codeStructure.totalSourceLoc} + ${a.codeStructure.testFiles} / ${a.testCoverage.testCases}. (Vanilla front-loads code, cladding front-loads spec — both converge by M2.)`,
  );
  return lines.join('\n');
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

// ──────────────────────────────────────────────────────────────────
// Outcome-quality renderer (F-ba2e05)
//
// Two sub-tables: drift catch + AI query benchmark. Plus a short
// "what this means" narrative that quantifies cladding-exclusive
// catches and AI-agent productivity.
// ──────────────────────────────────────────────────────────────────

function renderOutcomeSection(outcome: OutcomeReportInput): string {
  const lines: string[] = [];

  // Drift catch table (DI-1 ~ DI-4 × A,B)
  lines.push('### Drift Injection');
  lines.push('');
  lines.push('Each row = one realistic drift event injected into both groups at M2+. "Caught" means at least one new error/warn-level detector finding emerged after the injection.');
  lines.push('');
  lines.push('| Scenario | A (Cladding) caught? | A new detectors | B (Vanilla) caught? | B new detectors |');
  lines.push('|---|:---:|---|:---:|---|');
  const byId = new Map<string, {a?: DriftCatchResult; b?: DriftCatchResult}>();
  for (const r of outcome.driftResults) {
    const entry = byId.get(r.scenarioId) ?? {};
    if (r.group === 'A') entry.a = r;
    else entry.b = r;
    byId.set(r.scenarioId, entry);
  }
  for (const id of ['DI-1', 'DI-2', 'DI-3', 'DI-4']) {
    const entry = byId.get(id);
    if (!entry) continue;
    const aCaught = entry.a ? (entry.a.caught ? '✅' : '·') : 'N/A';
    const aDet = entry.a ? entry.a.newDetectors.slice(0, 3).join(', ') || '—' : 'N/A';
    const bCaught = entry.b ? (entry.b.caught ? '✅' : '·') : 'N/A';
    const bDet = entry.b ? entry.b.newDetectors.slice(0, 3).join(', ') || '—' : 'N/A';
    const name = entry.a?.scenarioName ?? entry.b?.scenarioName ?? id;
    lines.push(`| ${id} ${escapePipe(name)} | ${aCaught} | ${escapePipe(aDet)} | ${bCaught} | ${escapePipe(bDet)} |`);
  }
  lines.push('');

  // Aggregate stats
  const aCaughtCount = outcome.driftResults.filter((r) => r.group === 'A' && r.caught).length;
  const aTotalCount = outcome.driftResults.filter((r) => r.group === 'A').length;
  const bCaughtCount = outcome.driftResults.filter((r) => r.group === 'B' && r.caught).length;
  const bTotalCount = outcome.driftResults.filter((r) => r.group === 'B').length;
  const cladExclusive = outcome.driftResults.filter((r) => {
    if (r.group !== 'A' || !r.caught) return false;
    const bMatch = outcome.driftResults.find((x) => x.group === 'B' && x.scenarioId === r.scenarioId);
    return !bMatch || !bMatch.caught;
  }).length;
  lines.push(`**Catch rate**: A = ${aCaughtCount}/${aTotalCount} · B = ${bCaughtCount}/${bTotalCount} · **cladding-exclusive catches = ${cladExclusive}**`);
  lines.push('');

  // AI query benchmark table
  lines.push('### AI-Query Productivity');
  lines.push('');
  lines.push('Each row = one domain question. "Files opened" = deterministic file-IO an answer function performed to answer; lower is better. "answered=N" means the tree contained no answer.');
  lines.push('');
  lines.push('| Question | A files opened | A answer | B files opened | B answer |');
  lines.push('|---|---:|---|---:|---|');
  const aAnswers = outcome.queryResults.get('A') ?? [];
  const bAnswers = outcome.queryResults.get('B') ?? [];
  for (let i = 0; i < Math.max(aAnswers.length, bAnswers.length); i++) {
    const a = aAnswers[i];
    const b = bAnswers[i];
    const q = a?.question ?? b?.question ?? '';
    const qid = a?.questionId ?? b?.questionId ?? `Q${i + 1}`;
    const aFiles = a ? (a.answered ? String(a.filesOpened) : 'N') : 'N';
    const aAns = a ? truncate(a.answer, 60) : '—';
    const bFiles = b ? (b.answered ? String(b.filesOpened) : 'N') : 'N';
    const bAns = b ? truncate(b.answer, 60) : '—';
    lines.push(`| ${qid} ${escapePipe(truncate(q, 50))} | ${aFiles} | ${escapePipe(aAns)} | ${bFiles} | ${escapePipe(bAns)} |`);
  }
  lines.push('');

  // Aggregate query stats
  const aAnswerable = aAnswers.filter((q) => q.answered).length;
  const aLowCost = aAnswers.filter((q) => q.answered && q.filesOpened <= 1).length;
  const bAnswerable = bAnswers.filter((q) => q.answered).length;
  const bLowCost = bAnswers.filter((q) => q.answered && q.filesOpened <= 1).length;
  lines.push(`**Answerability**: A = ${aAnswerable}/${aAnswers.length} answered · B = ${bAnswerable}/${bAnswers.length} answered`);
  lines.push(`**Low-cost answers (≤1 file)**: A = ${aLowCost}/${aAnswers.length} · B = ${bLowCost}/${bAnswers.length}`);
  lines.push('');

  // What it means
  lines.push('### What this means');
  lines.push('');
  lines.push(`- **H6 — Cladding catches drift vanilla misses**: ${cladExclusive}/${aTotalCount} cladding-exclusive catches. The non-exclusive catches (where both groups catch) are toolchain-only detectors like HARDCODED_SECRET that fire regardless of spec presence — useful baseline but not where cladding's design pays off.`);
  lines.push(`- **H7 — Cladding makes AI agents productive**: A answers ${aLowCost}/${aAnswers.length} queries from ≤1 file; B answers ${bLowCost}/${bAnswers.length}. For the unanswerable B queries, the tree has no canonical source — an AI agent would either give up or hallucinate from inferred context.`);
  lines.push('- **H8 — Iron Law gates measure detector activity, not codebase health**: when `clad check --strict` runs against vanilla, spec-required detectors silently report 0 findings. The same gate on cladding-managed code uses all 25 detectors. Same gate label, very different evaluation surface.');
  return lines.join('\n');
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// ──────────────────────────────────────────────────────────────────
// Snapshot file gate
//
// Case tests call `writeOrAssertReport(reportAbsPath, generated)`:
//   - When `UPDATE_AB_REPORTS=1` env var is set, the file is
//     (re)written so the developer can intentionally update it.
//   - Otherwise the existing file's content is compared to the
//     generated content. Diff → throw → vitest failure.
// This is the standard committed-snapshot pattern. CI keeps the
// committed report deterministic; local devs can refresh with the
// env var when metrics shift legitimately.
// ──────────────────────────────────────────────────────────────────

export function writeOrAssertReport(reportAbsPath: string, generated: string): void {
  const shouldUpdate = process.env.UPDATE_AB_REPORTS === '1';
  if (shouldUpdate) {
    mkdirSync(dirname(reportAbsPath), {recursive: true});
    writeFileSync(reportAbsPath, generated);
    return;
  }
  if (!existsSync(reportAbsPath)) {
    throw new Error(
      `writeOrAssertReport: ${reportAbsPath} does not exist. Run with UPDATE_AB_REPORTS=1 to create it.`,
    );
  }
  const onDisk = readFileSync(reportAbsPath, 'utf8');
  if (onDisk !== generated) {
    throw new Error(
      `writeOrAssertReport: ${reportAbsPath} content drift. ` +
        'Re-run with UPDATE_AB_REPORTS=1 if the metric changes are intentional. ' +
        `First diff:\n${firstDiff(onDisk, generated)}`,
    );
  }
}

function firstDiff(a: string, b: string): string {
  const al = a.split('\n');
  const bl = b.split('\n');
  for (let i = 0; i < Math.max(al.length, bl.length); i++) {
    if (al[i] !== bl[i]) {
      return `  L${i + 1} on-disk: ${(al[i] ?? '<EOF>').slice(0, 120)}\n  L${i + 1} generated: ${(bl[i] ?? '<EOF>').slice(0, 120)}`;
    }
  }
  return '  (no line diff — content lengths differ in trailing newline)';
}
